version: "2"

services:
  ide:
    image: monstrs/cloud9
    volumes:
      - ./:/workspace
    ports:
      - "8497:80"

  install:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./.netrc:/root/.netrc
    entrypoint: npm install

  npm:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm

  dev:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm run dev
    ports:
      - "3040:3030"

  dev-local:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm run dev
    environment:
      - API_URL=http://localhost:3000/
    ports:
      - "3040:3030"

  build:
    image: node
    working_dir: /workspace
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/workspace
    entrypoint: npm run build

  demo:
    image: node
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: npm start
    ports:
      - "3000:3000"

  server:
    build: ./
    ports:
      - "3000:3000"
